version: '3.8'
services:
  chat_postgres:
    image: postgres:17
    container_name: chat_postgres
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpassword
      - POSTGRES_DB=chatapp
    ports:
      - "5432:5432"
    volumes:
      - chatapp_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: chat_backend
  #   depends_on:
  #     - chat_postgres
  #   ports:
  #     - "3000:3000"
  #   # Avoid overwriting node_modules in the container
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  chatapp_data:
