version: '3.8'
services:
  db:
    image: postgres:17
    container_name: chat_postgres
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpassword
      - POSTGRES_DB= chatapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data
  
  backend:
    build: 
      context:  .
      dockerfile: Dockerfile
    container_name: chat_backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL= "postgresql://chatuser:chatpassword@db:5432/chatdb"
    volumes:
      - .:/ app
volumes:
  db_data: